### ISSUE TITLE
Checking the translation for spanish 

### ISSUE THREAD

**Issue by Milchreis** [Milchreis/JCopy#3]
This translation should be checked by a native speaker:
https://github.com/Milchreis/JCopy/blob/master/src/main/resources/MessagesBundle_es_ES.properties

**Comment by SantiagoJimenezQ** [comment]
Hey, @Milchreis, I'm a native Spanish speaker. I'll check it and fix some errors.

**Comment by SantiagoJimenezQ** [comment]
#9
