### ISSUE TITLE
Checking the translation into Polish

### ISSUE THREAD

**Issue by Milchreis** [Milchreis/JCopy#5]
This translation should be checked by a native speaker:
https://github.com/Milchreis/JCopy/blob/master/src/main/resources/MessagesBundle_pl_PL.properties

**Comment by TomaszWegrzyn** [comment]
Hi, @Milchreis, I am native polish speaker. I can check them(actually they need fixes for sure - I will fix them)

Can you add add [hacktoberfest topic to the repository](https://hacktoberfest.digitalocean.com/hacktoberfest-update) in the meantime?
